apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracer
  namespace: example-app
spec:
  selector:
    matchLabels:
      app: sample
  replicas: 1
  template:
    metadata:
      labels:
        app: sample
    spec:
      containers:
        - name: tracer
          # change the following to your container image:
          image: "ACCOUNTID.dkr.ecr.REGION.amazonaws.com/x-ray-sample-app:latest"
          ports:
          - containerPort: 8080
          env:
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: "adot-collector.adot-col:4317"
---
apiVersion: v1
kind: Service
metadata:
  name: tracer
  namespace: example-app
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: sample

