{
 "title": "RDS-PI-V1",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Top Load Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Top Session Type",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "metricName": "session_type",
     "namespace": "sharajag/PerfInsights-test-v4",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Top Users",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "metricName": "user",
     "namespace": "sharajag/PerfInsights-test-v4",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Top Wait event",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "metricName": "wait_event",
     "namespace": "sharajag/PerfInsights-test-v4",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Top Application",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "metricName": "application",
     "namespace": "sharajag/PerfInsights-test-v4",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Top SQL",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "metricName": "sql_tokenized",
     "namespace": "sharajag/PerfInsights-test-v4",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "sharajag/PerfInsights-test-v4", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "property": { "name": "db.sql_tokenized.statement", "type": "string" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "limit": 10,
      "orderBy": { "name": "AVG", "type": "function" },
      "orderByDirection": "DESC",
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "sql_tokenized", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT AVG(sql_tokenized) FROM \"sharajag/PerfInsights-test-v4\" GROUP BY \"db.sql_tokenized.statement\" ORDER BY AVG() DESC LIMIT 10",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Top Database",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "metricName": "name",
     "namespace": "sharajag/PerfInsights-test-v4",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Top Host",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "metricName": "host",
     "namespace": "sharajag/PerfInsights-test-v4",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  { "title": "Database load", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Database load - SQL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "dimensions": {
      "db.sql_tokenized.statement": "*"
     },
     "metricName": "sql_tokenized",
     "namespace": "sharajag/PerfInsights-test-v4",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Database load - User",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "metricName": "user",
     "namespace": "sharajag/PerfInsights-test-v4",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Database",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "metricName": "name",
     "namespace": "sharajag/PerfInsights-test-v4",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Wait event",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "dimensions": { "db.wait_event.name": "*" },
     "metricName": "wait_event",
     "namespace": "sharajag/PerfInsights-test-v4",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Database Load - Application",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "metricName": "application",
     "namespace": "sharajag/PerfInsights-test-v4",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Minimum"
    }
   ]
  },
  {
   "title": "Session Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "metricName": "session_type",
     "namespace": "sharajag/PerfInsights-test-v4",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Database Load - Host",
   "type": "timeseries",
   "description": "Performance Insight metrics",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "metricName": "host",
     "namespace": "sharajag/PerfInsights-test-v4",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  }
 ]
}