{
 "title": "ho11y",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "[LOGS] invokes",
   "type": "logs",
   "description": "From CloudWatch",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expression": "fields @message | filter @message like /invoked/",
     "logGroupNames": [ "ho11y-fluentbit" ],
     "queryMode": "Logs",
     "region": "default"
    }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "[METRICS] invokes by HTTP status code",
   "type": "graph",
   "description": "From AMP (Prometheus)",
   "gridPos": { "h": 14, "w": 11, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by(http_status_code) (rate(ho11y_total[5m]))",
     "legendFormat": "{{http_status_code}}"
    }
   ]
  },
  {
   "title": "[METRICS] total invoke payloads",
   "type": "graph",
   "description": "From AMP (Prometheus)",
   "gridPos": { "h": 14, "w": 6, "x": 11, "y": 10 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "sum by (k8s_pod) (rate(ho11y_downstream_payload_bytes_sum[5m]))"
    }
   ]
  },
  {
   "title": "[METRICS]  downstream invoke performance",
   "type": "graph",
   "description": "From AMP (Prometheus)",
   "gridPos": { "h": 14, "w": 7, "x": 17, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(ho11y_downstream_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(ho11y_downstream_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  { "title": "Traces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "[TRACES] service map",
   "type": "nodeGraph",
   "description": "From X-Ray",
   "gridPos": { "h": 18, "w": 7, "x": 0, "y": 25 },
   "targets": [
    {
     "group": {
      "FilterExpression": null,
      "GroupARN": "arn:aws:xray:eu-west-1:148658015984:group/Default",
      "GroupName": "Default",
      "InsightsConfiguration": {
       "InsightsEnabled": true,
       "NotificationsEnabled": true
      }
     },
     "query": "\n",
     "region": "default"
    }
   ]
  },
  {
   "title": "[TRACES] errors",
   "type": "table",
   "description": "From X-Ray",
   "gridPos": { "h": 18, "w": 17, "x": 7, "y": 25 },
   "targets": [
    {
     "group": {
      "FilterExpression": null,
      "GroupARN": "arn:aws:xray:eu-west-1:148658015984:group/Default",
      "GroupName": "Default",
      "InsightsConfiguration": {
       "InsightsEnabled": true,
       "NotificationsEnabled": true
      }
     },
     "query": "service(\"frontend\") AND http.status != 200",
     "region": "default"
    }
   ]
  }
 ]
}