name: CW Metric Stream 
on:
  # enable manual trigger via button in GitHub actions
  workflow_dispatch:
  # enable auto trigger based on path and branch
  push:
    paths: 
      - 'sandbox/CWMetricStreamExporter/**'
      - '.github/workflows/**'
  pull_request:
    paths: 
      - 'sandbox/CWMetricStreamExporter/**'
      - '.github/workflows/**'
jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    env: 
      working-directory: './sandbox/CWMetricStreamExporter'
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.17

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: cd ${{env.working-directory}} && cd lambda && go mod download

    - name: Go Build
      run: cd ${{env.working-directory}} && make go_build

    - name: Go Test
      run: cd ${{env.working-directory}} && make go_test

    - name: NPM Build
      run: cd ${{env.working-directory}} && make npm_build

    - name: NPM Lint
      run: cd ${{env.working-directory}} && make npm_lint
      
    - name: NPM Test
      run: cd ${{env.working-directory}} && make npm_test
